% Create a figure and axis upon which plots can be made
function [fig, ax] = CreateAxis(name, varargin)
    fig = figure('Name', name, 'NumberTitle', 'off', 'Color', [1, 1, 1], 'MenuBar', 'none', ...
        'ToolBar', 'none', 'DockControls', 'off', 'Position', [0, 0, 1200, 800], ...
        'InvertHardcopy', 'off');
    movegui(fig, 'center');
    ax = axes(fig, 'Box', 'on', 'TickDir', 'out', 'TickLength', [.005, .01], ...
        'XGrid', 'on', 'YGrid', 'on', 'GridColor', [.5,.5,.5], 'GridAlpha', 1, ...
        'GridLineStyle', ':', 'FontSize', 12);
    hold on;
    title(ax, name, 'FontSize', 24, 'FontWeight', 'bold', varargin{:});
end